version: '3'

services:
  ml-service:
    build:
      context: ./ml
      dockerfile: Dockerfile
    container_name: ml-container

    depends_on:
      - test-service


  wavelet-service:
    build:
      context: ./wavelet_filtering
      dockerfile: Dockerfile
    container_name: wavelet-container

    depends_on:
      - test-service


  app-service:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "8050:8050"

    depends_on:
      - test-service


  test-service:
    build:
      context: ./test_bd
      dockerfile: Dockerfile
    container_name: test-container

    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: futures_user
      POSTGRES_PASSWORD: aaa
      POSTGRES_DB: analys
    ports:
      - "5433:5432"